### ISSUE TITLE
Confusing "usage" section

### ISSUE THREAD

**Issue by dawsonbotsford** [abrelsfo/Creepin#1]
The usage section contains parenthesis and brackets for the terminal usage section. node code would contain parenthesis and brackets, but shell should not.

    Usage
    $ creepin([input], [flags])

    $ creepin(['abrelsfo'], ['-g', '-n'])
     opens user profile for abrelsfo on Github and npm

<br>

Perhaps this is what you intended instead?:

Usage
    $ creepin [input]  [flags] 

    $ creepin ['abrelsfo'] ['-g', '-n'] 
     opens user profile for abrelsfo on Github and npm

**Comment by abrelsfo** [comment]
@dawsonbotsford I changed it to 

Usage
$ creepin [input] [flags] 

and then added some more description as to how it works.
On the CLI you don't need the brackets since meow will automatically split the flags from the other stuff

**Comment by dawsonbotsford** [comment]
Consider closing issues like this via a commit message. If you commit message for this fix was "closes #1" it auto-closes when pushed to master and references which commit closed the issue right here.

Read more: https://help.github.com/articles/closing-issues-via-commit-messages/
